# Generated by Django 4.2 on 2023-04-27 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BloodSugarLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('blood_sugar_am_time', models.TimeField(blank=True, null=True)),
                ('blood_sugar_am_level', models.FloatField(blank=True, null=True)),
                ('breakfast_menu', models.CharField(blank=True, max_length=255, null=True)),
                ('breakfast_time', models.TimeField(blank=True, null=True)),
                ('lunch_menu', models.CharField(blank=True, max_length=255, null=True)),
                ('lunch_time', models.TimeField(blank=True, null=True)),
                ('dinner_menu', models.CharField(blank=True, max_length=255, null=True)),
                ('dinner_time', models.TimeField(blank=True, null=True)),
                ('blood_sugar_pm_time', models.TimeField(blank=True, null=True)),
                ('blood_sugar_pm_level', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
