# Generated by Django 4.2 on 2023-04-30 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_user_full_name_alter_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='second_password_answer_1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='second_password_answer_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='second_password_answer_3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='second_password_question_1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='second_password_question_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='second_password_question_3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
