# Generated by Django 4.2 on 2023-04-30 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_user_second_password_answer_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_security_question_required',
            field=models.BooleanField(default=False),
        ),
    ]
